Milestone friendships v1
ABDELLANI-Youcef/ror-social-scaffold pull request #2
Opened 2020-10-28 15:50 UTC by ABDELLANI-Youcef

## Milestone friendships v1
In this milestone we make:
- A friendship model, associations, and migration;
- A friendship controller and view;
- The possibility to send a friendship invitation and to accept or decline this invitation;
- A spec tests.

2020-10-28 15:59 UTC, ABDELLANI-Youcef commented
We made a linter check in the local environment and everything was fine, but in Github, the linter tests didn't start.

2020-10-28 18:06 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
### Hi @ABDELLANI-Youcef and @Ceci007 :clap: :clap:
#### Well done :muscle:  You have done a good job so far. However, there some issues you need to fix before this project can be approved.

- **_Enable Linter_**

- **_Posts timeline should include only the posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))_**

#### Optional:
- **_I think it will improve the user experience if the accept and reject buttons are next to the appropriate user(in "ALL USERS") in case of the friend request instead of click on the "FRIEND REQUESTS" link before a user can accept or reject a friend request_**

**_Fix these and submit them for review._**

#### _Reviewed by Temitayo Adeleke_

2020-10-28 18:06 UTC, lekegitrepo commented on config/database.yml
> +  username: postgres
- **_Remove `username: postgres` it affects the migration on the other computer_**

2020-10-28 18:06 UTC, lekegitrepo commented on config/database.yml
> +  username: postgres
- **_Remove `username: postgres` it affects the migration on the other computer_**

2020-10-28 22:27 UTC, ABDELLANI-Youcef commented
Hello, could you help us to enable linter on GitHub? In fact, we could run the linter in the local environment (our laptops) but when we push the project on GitHub we found that the tests are not running even though we set the linter all over again.

2020-10-29 03:12 UTC, voscarmv requested changes
Hi, team. Great job applying the necessary changes requested by the previous TSE. However, you still must fix your linters somehow.

I find this to be a very strange bug, because I've actually created a copy of your repository to see what the problem was, but in my case, the linters seem to be working perfectly.

Here's my version of your PR for future reference: https://github.com/voscarmv/tse_ror_test/pull/1

Here are a few suggestions to fix this issue:

1. Try modifying the linter .yml files slightly, and then pushing, to see if this activates the GitHub automated checks.
2. If all else fails, contact me through Slack. I might be able to provide you further technical support.

All the rest of the project requirements seem to be in order. This is the one last issue remaining.

2020-10-29 14:21 UTC, closed without merging